AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda with LangGraph Agent

Parameters:
  TonApiKey:
    Type: String
    Description: "API Key from tonapi.io"
    NoEcho: true
  TelegramBotToken:
    Type: String
    Description: "Token from BotFather"
    NoEcho: true
  LangfuseSecretKey:
    Type: String
    Description: "Langfuse Secret Key (sk-lf-...)"
    NoEcho: true
  LangfusePublicKey:
    Type: String
    Description: "Langfuse Public Key (pk-lf-...)"
    NoEcho: true
  LangfuseHost:
    Type: String
    Description: "Langfuse Host URL"
    Default: "https://cloud.langfuse.com"

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Secrets for Tonpixo"
      SecretString: !Sub '{"TONAPI_KEY":"${TonApiKey}","TELEGRAM_BOT_TOKEN":"${TelegramBotToken}","LANGFUSE_SECRET_KEY":"${LangfuseSecretKey}","LANGFUSE_PUBLIC_KEY":"${LangfusePublicKey}","LANGFUSE_HOST":"${LangfuseHost}"}'

  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users"
      AttributeDefinitions:
        - AttributeName: telegram_id
          AttributeType: N
      KeySchema:
        - AttributeName: telegram_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-jobs"
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 120
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          # Lambda Web Adapter configuration for response streaming
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_LWA_PORT: 8080
          # Application configuration
          JOBS_TABLE: !Ref JobsTable
          USERS_TABLE: !Ref UsersTable
          JOBS_QUEUE_URL: !Ref JobsQueue
          DATA_BUCKET: !Ref DataBucket
          SECRET_NAME: !Ref AppSecrets
          # Langfuse configuration
          LANGFUSE_TRACING_ENVIRONMENT: !Ref "AWS::StackName"
          # Matplotlib config - use /tmp for cache (Lambda requirement)
          MPLCONFIGDIR: /tmp/matplotlib
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobsQueue.QueueName
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - S3WritePolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref AppSecrets
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
          MaxAge: 86400
        InvokeMode: RESPONSE_STREAM
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./worker
      Handler: worker.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          DATA_BUCKET: !Ref DataBucket
          SECRET_NAME: !Ref AppSecrets
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - S3WritePolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref AppSecrets
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 1

  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL (use for non-streaming requests)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionUrl:
    Description: "Lambda Function URL (use for streaming chat)"
    Value: !GetAtt FastApiFunctionUrl.FunctionUrl