AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda with LangGraph Agent

Parameters:
  TonApiKey:
    Type: String
    Description: "API Key from tonapi.io"
    NoEcho: true
  TelegramBotToken:
    Type: String
    Description: "Token from BotFather"
    NoEcho: true
  LangfuseSecretKey:
    Type: String
    Description: "Langfuse Secret Key (sk-lf-...)"
    NoEcho: true
  LangfusePublicKey:
    Type: String
    Description: "Langfuse Public Key (pk-lf-...)"
    NoEcho: true
  LangfuseHost:
    Type: String
    Description: "Langfuse Host URL"
    Default: "https://cloud.langfuse.com"

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users"
      AttributeDefinitions:
        - AttributeName: telegram_id
          AttributeType: N
      KeySchema:
        - AttributeName: telegram_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-jobs"
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Timeout: 120
      MemorySize: 1024
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          USERS_TABLE: !Ref UsersTable
          JOBS_QUEUE_URL: !Ref JobsQueue
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          DATA_BUCKET: !Ref DataBucket
          # Langfuse configuration
          LANGFUSE_SECRET_KEY: !Ref LangfuseSecretKey
          LANGFUSE_PUBLIC_KEY: !Ref LangfusePublicKey
          LANGFUSE_HOST: !Ref LangfuseHost
          LANGFUSE_TRACING_ENVIRONMENT: !Ref "AWS::StackName"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobsQueue.QueueName
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
        InvokeMode: RESPONSE_STREAM
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: worker.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          DATA_BUCKET: !Ref DataBucket
          TONAPI_KEY: !Ref TonApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - S3WritePolicy:
            BucketName: !Ref DataBucket
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 1

  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL (use for non-streaming requests)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionUrl:
    Description: "Lambda Function URL (use for streaming chat)"
    Value: !GetAtt FastApiFunctionUrl.FunctionUrl