AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda with LangGraph Agent

Parameters:
  DeploymentProfile:
    Type: String
    Description: "Deployment profile to select branch-specific secrets"
    AllowedValues:
      - main
      - dev
    Default: main
  TonApiKey:
    Type: String
    Description: "API Key from tonapi.io"
    NoEcho: true
  TelegramBotTokenMain:
    Type: String
    Description: "Telegram Bot token for main branch deployments"
    NoEcho: true
  TelegramBotTokenDev:
    Type: String
    Description: "Telegram Bot token for dev branch deployments"
    NoEcho: true
  LangfuseSecretKey:
    Type: String
    Description: "Langfuse Secret Key (sk-lf-...)"
    NoEcho: true
  LangfusePublicKey:
    Type: String
    Description: "Langfuse Public Key (pk-lf-...)"
    NoEcho: true
  LangfuseHost:
    Type: String
    Description: "Langfuse Host URL"
    Default: "https://cloud.langfuse.com"

Conditions:
  IsDevProfile: !Equals [!Ref DeploymentProfile, dev]

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  AppSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: "Secrets for Tonpixo"
      SecretString:
        Fn::Sub:
          - '{"TONAPI_KEY":"${TonApiKey}","TELEGRAM_BOT_TOKEN":"${ResolvedTelegramBotToken}","LANGFUSE_SECRET_KEY":"${LangfuseSecretKey}","LANGFUSE_PUBLIC_KEY":"${LangfusePublicKey}","LANGFUSE_HOST":"${LangfuseHost}"}'
          - ResolvedTelegramBotToken: !If [IsDevProfile, !Ref TelegramBotTokenDev, !Ref TelegramBotTokenMain]

  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-users"
      AttributeDefinitions:
        - AttributeName: telegram_id
          AttributeType: N
      KeySchema:
        - AttributeName: telegram_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-jobs"
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 120
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          # Lambda Web Adapter configuration for response streaming
          AWS_LWA_INVOKE_MODE: RESPONSE_STREAM
          AWS_LWA_PORT: 8080
          # Application configuration
          JOBS_TABLE: !Ref JobsTable
          USERS_TABLE: !Ref UsersTable
          CHATS_TABLE: !Ref ChatsTable
          MESSAGES_TABLE: !Ref MessagesTable
          FAVOURITES_TABLE: !Ref FavouritesTable
          JOBS_QUEUE_URL: !Ref JobsQueue
          DATA_BUCKET: !Ref DataBucket
          SECRET_NAME: !Ref AppSecrets
          # Athena configuration
          ATHENA_WORKGROUP: !Ref AthenaWorkGroup
          GLUE_DATABASE: !Ref GlueDatabase
          # Langfuse configuration
          LANGFUSE_TRACING_ENVIRONMENT: !Sub "${AWS::StackName}-${DeploymentProfile}"
          DEPLOYMENT_PROFILE: !Ref DeploymentProfile
          # Matplotlib config - use /tmp for cache (Lambda requirement)
          MPLCONFIGDIR: /tmp/matplotlib
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ChatsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
        - DynamoDBCrudPolicy:
            TableName: !Ref FavouritesTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobsQueue.QueueName
        - S3ReadPolicy:
            BucketName: !Ref DataBucket
        - S3WritePolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
                - bedrock:InvokeModelWithResponseStream
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref AppSecrets
        - Statement:
            - Effect: Allow
              Action:
                - athena:StartQueryExecution
                - athena:GetQueryExecution
                - athena:GetQueryResults
                - glue:GetTable
                - glue:GetPartitions
              Resource: "*"
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "*"
          AllowHeaders:
            - "*"
          MaxAge: 86400
        InvokeMode: RESPONSE_STREAM
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: latest

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 300
      MemorySize: 1024
      Architectures:
        - arm64
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          DATA_BUCKET: !Ref DataBucket
          SECRET_NAME: !Ref AppSecrets
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - S3WritePolicy:
            BucketName: !Ref DataBucket
        - Statement:
            - Effect: Allow
              Action: secretsmanager:GetSecretValue
              Resource: !Ref AppSecrets
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 1
    Metadata:
      Dockerfile: worker/Dockerfile
      DockerContext: .
      DockerTag: latest

  DataBucket:
    Type: AWS::S3::Bucket

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: !Sub "${AWS::StackName}-workgroup"
      WorkGroupConfiguration:
        ResultConfiguration:
          OutputLocation: !Sub "s3://${DataBucket}/athena-results/"

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub "tonpixo_db_${DeploymentProfile}"

  TransactionsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "transactions"
        TableType: "EXTERNAL_TABLE"
        Parameters:
          projection.enabled: "true"
          projection.job_id.type: "injected"
          classification: "parquet"
        StorageDescriptor:
          Location: !Sub "s3://${DataBucket}/data/transactions/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          Columns:
            - Name: "datetime"
              Type: "timestamp"
            - Name: "event_id"
              Type: "string"
            - Name: "type"
              Type: "string"
            - Name: "direction"
              Type: "string"
            - Name: "asset"
              Type: "string"
            - Name: "amount"
              Type: "double"
            - Name: "label"
              Type: "string"
            - Name: "category"
              Type: "string"
            - Name: "wallet_comment"
              Type: "string"
            - Name: "sender"
              Type: "string"
            - Name: "receiver"
              Type: "string"
            - Name: "comment"
              Type: "string"
            - Name: "status"
              Type: "string"
            - Name: "is_scam"
              Type: "boolean"
        PartitionKeys:
          - Name: "job_id"
            Type: "string"

  JettonsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "jettons"
        TableType: "EXTERNAL_TABLE"
        Parameters:
          projection.enabled: "true"
          projection.job_id.type: "injected"
          classification: "parquet"
        StorageDescriptor:
          Location: !Sub "s3://${DataBucket}/data/jettons/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          Columns:
            - Name: "jetton_address"
              Type: "string"
            - Name: "symbol"
              Type: "string"
            - Name: "name"
              Type: "string"
            - Name: "balance"
              Type: "double"
            - Name: "balance_raw"
              Type: "string"
            - Name: "decimals"
              Type: "int"
            - Name: "price_usd"
              Type: "double"
            - Name: "value_usd"
              Type: "double"
            - Name: "verified"
              Type: "boolean"
            - Name: "image_url"
              Type: "string"
            - Name: "wallet_address"
              Type: "string"
            - Name: "type"
              Type: "string"
        PartitionKeys:
          - Name: "job_id"
            Type: "string"

  NftsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: "nfts"
        TableType: "EXTERNAL_TABLE"
        Parameters:
          projection.enabled: "true"
          projection.job_id.type: "injected"
          classification: "parquet"
        StorageDescriptor:
          Location: !Sub "s3://${DataBucket}/data/nfts/"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
          Columns:
            - Name: "nft_address"
              Type: "string"
            - Name: "index"
              Type: "int"
            - Name: "name"
              Type: "string"
            - Name: "description"
              Type: "string"
            - Name: "collection_address"
              Type: "string"
            - Name: "collection_name"
              Type: "string"
            - Name: "verified"
              Type: "boolean"
            - Name: "image_url"
              Type: "string"
            - Name: "metadata_url"
              Type: "string"
            - Name: "owner_address"
              Type: "string"
            - Name: "sale_price_ton"
              Type: "double"
            - Name: "sale_market"
              Type: "string"
        PartitionKeys:
          - Name: "job_id"
            Type: "string"

  ChatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-chats"
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: updated_at
          AttributeType: S
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserChatsIndex
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: updated_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST

  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-messages"
      AttributeDefinitions:
        - AttributeName: chat_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: chat_id
          KeyType: HASH
        - AttributeName: created_at
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  FavouritesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-favourites"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: address
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: address
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL (use for non-streaming requests)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FunctionUrl:
    Description: "Lambda Function URL (use for streaming chat)"
    Value: !GetAtt FastApiFunctionUrl.FunctionUrl
