AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI on AWS Lambda

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Resources:
  JobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 300

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-jobs"
      AttributeDefinitions:
        - AttributeName: job_id
          AttributeType: S
      KeySchema:
        - AttributeName: job_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          JOBS_QUEUE_URL: !Ref JobsQueue
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt JobsQueue.QueueName
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  WorkerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: worker.lambda_handler
      Runtime: python3.11
      Timeout: 300
      MemorySize: 512
      Environment:
        Variables:
          JOBS_TABLE: !Ref JobsTable
          DATA_BUCKET: !Ref DataBucket
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref JobsTable
        - S3WritePolicy:
            BucketName: !Ref DataBucket
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt JobsQueue.Arn
            BatchSize: 1

  DataBucket:
    Type: AWS::S3::Bucket

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"